### ISSUE TITLE
integrate with Syntastic

### ISSUE THREAD

**Issue by sunaku** [machakann/vim-vimhelplint#2]
Integrating with [Syntastic](https://github.com/scrooloose/syntastic) would allow the linter to run _while_ you compose help files. :bulb:

**Comment by machakann** [comment]
Now it can cooperate with Syntastic. Please add the line in your vimrc.

``` vim
let g:syntastic_help_checkers = ['vimhelplint']
```

Then it should be OK. Could you check?

By the way vimhelplint might be too heavy, use it carefully.

**Comment by sunaku** [comment]
Thanks! :bow: I tried adding that line and restarted Vim (both NeoVim and regular Vim) but nothing happens when I save my help file or run `:SyntasticCheck` manually. :sweat:  Here is some additional information:

``` vim
:SyntasticInfo
Syntastic version: 3.7.0-84 (Vim 704, Linux)
Info for filetype: help
Global mode: active
Filetype help is active
The current file will be checked automatically
Available checker: vimhelplint
Currently enabled checker: vimhelplint
Press ENTER or type command to continue
```

**Comment by machakann** [comment]
Thanks for the information. It looks the vimhelplint is successfully recognized by Syntastic. Maybe some problems are on vimhelplint, mmm...

Could you check whether `:VimhelpLint!` command can find any errors in the same help file or not? Because vimhelplint suppresses command-line messages in cooperation with Syntastic, if no errors has been found it looks nothing happens and nothing displayed. If possible I want you to check with embedding an wrong tag to your help file.

**Comment by sunaku** [comment]
Yes, here is the result:

``` vim
:VimhelpLint!
vimhelplint: 18 errors have been found!
```

Upon further thought, I now feel that perhaps integration with Syntastic is unnecessary :elephant: because I can easily set up a `BufWritePost` autocommand to call `:VimhelpLint` in my vimrc instead :mouse:, as follows:

``` vim
autocmd BufWritePost */doc/*.txt :silent VimhelpLint!
```

Sorry for wasting your time with this feature request. :cold_sweat:

**Comment by machakann** [comment]
:laughing: You're totally right. It is the easiest way without any doubt.
I should have come up with that! I will add the line to documents later. Thanks!
