### ISSUE TITLE
glob() might be too old

### ISSUE THREAD

**Issue by blueyed** [machakann/vim-vimhelplint#5]
You are using the `list` argument with `glob()` (https://github.com/machakann/vim-vimhelplint/blob/ad742bafba595e6b14b3faa92b08c8838acf9912/ftplugin/help_lint.vim#L52), which might not be supported, e.g. with the Vim on Travis: https://travis-ci.org/neomake/neomake/jobs/157519302#L405-L413

I think this could just use `split()` here, or a wrapper like with other functions.

But I also do not understand what that code is trying to achieve there: I've only noticed that it would still link `doc/neomake.txt` although I've called it for `doc/neomake2.txt` explicitly (for testing).

**Comment by machakann** [comment]
The `{list}` argument was added at vim-7.3.465, it looks the Vim on Travis is older than that probably. I will try to make it work, but probably it is not enough only to replace glob() function to wrapper. Please wait a moment or just bring newer one.

By the way, do you know the exact version of Vim on Travis?

**Comment by machakann** [comment]
Oh, and vimhelplint always works thorough a project. Actually it can not check in file unit, because if the project have multiple documents a document could have a link to another. Yes it is somehow silly, it should be able to be done only when it is required. However when I wrote this tiny script I have been satisfied as it is. I will think on it when I have time.

**Comment by blueyed** [comment]
Thanks for the fixes!
Travis has Vim 7.3.429: https://travis-ci.org/neomake/neomake/builds/158305346#L185

**Comment by machakann** [comment]
OK, it works safely  on Vim 7.3.429 now, at least in my PC. If you found any problem, please tell me. Thanks!
